/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DaoFractionalVote } from "./DaoFractionalVote";
export type { DaoMultisigVote } from "./DaoMultisigVote";
export type { DaoSimpleVote } from "./DaoSimpleVote";
