/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Mock } from "./ERC20Mock";
export type { MockFundToken } from "./MockFundToken";
export type { TargetContract } from "./TargetContract";
