/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iDaoSol from "./IDao.sol";
export type { iDaoSol };
export type { IDaoFractionalVote } from "./IDaoFractionalVote";
export type { IDaoMultisigVote } from "./IDaoMultisigVote";
export type { IDaoSimpleVote } from "./IDaoSimpleVote";
export type { IVotes } from "./IVotes";
