/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDaoSimpleVote,
  IDaoSimpleVoteInterface,
} from "../../../contracts/interfaces/IDaoSimpleVote";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "string",
        name: "daoURI",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "minimalDuration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "proposalCreationMinVotingPower",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint16",
            name: "numerator",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "denominator",
            type: "uint16",
          },
        ],
        internalType: "struct Fraction",
        name: "quorumFraction",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint16",
            name: "numerator",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "denominator",
            type: "uint16",
          },
        ],
        internalType: "struct Fraction",
        name: "minimumParticipationFraction",
        type: "tuple",
      },
      {
        internalType: "contract IERC5805",
        name: "token",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDaoSimpleVote__factory {
  static readonly abi = _abi;
  static createInterface(): IDaoSimpleVoteInterface {
    return new Interface(_abi) as IDaoSimpleVoteInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDaoSimpleVote {
    return new Contract(address, _abi, runner) as unknown as IDaoSimpleVote;
  }
}
