/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iDaoSol from "./IDao.sol";
export { IDaoFractionalVote__factory } from "./IDaoFractionalVote__factory";
export { IDaoMultisigVote__factory } from "./IDaoMultisigVote__factory";
export { IDaoSimpleVote__factory } from "./IDaoSimpleVote__factory";
export { IVotes__factory } from "./IVotes__factory";
