/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDaoErrors,
  IDaoErrorsInterface,
} from "../../../../contracts/interfaces/IDao.sol/IDaoErrors";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "AlreadyCastVote",
    type: "error",
  },
  {
    inputs: [],
    name: "AlreadyInitialized",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "InvalidAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidFraction",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidProposalId",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "proposer",
        type: "address",
      },
    ],
    name: "InvalidProposer",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "str",
        type: "string",
      },
    ],
    name: "InvalidString",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "InvalidUint256",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
    ],
    name: "InvalidVoteDuration",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidVoteParams",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "voteStart",
        type: "uint256",
      },
    ],
    name: "InvalidVoteStart",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidVoteType",
    type: "error",
  },
  {
    inputs: [],
    name: "NativeTokenDepositAmountMismatch",
    type: "error",
  },
  {
    inputs: [],
    name: "NoActions",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyProposerCanCancel",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
    ],
    name: "ProposalNotActive",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
    ],
    name: "ProposalNotSuccessful",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
    ],
    name: "TooLateToCancel",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "length",
        type: "uint256",
      },
    ],
    name: "TooManyActions",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
    ],
    name: "UnknownProposal",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
    ],
    name: "VotingNotActive",
    type: "error",
  },
] as const;

export class IDaoErrors__factory {
  static readonly abi = _abi;
  static createInterface(): IDaoErrorsInterface {
    return new Interface(_abi) as IDaoErrorsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDaoErrors {
    return new Contract(address, _abi, runner) as unknown as IDaoErrors;
  }
}
