/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDao__factory } from "./IDao__factory";
export { IDaoErrors__factory } from "./IDaoErrors__factory";
