/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockFundToken__factory } from "./MockFundToken__factory";
export { TargetContract__factory } from "./TargetContract__factory";
