/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  TargetContract,
  TargetContractInterface,
} from "../../../contracts/test/TargetContract";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "candidate",
        type: "address",
      },
    ],
    name: "CandidateOnboarded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "newValue",
        type: "uint256",
      },
    ],
    name: "ValueChanged",
    type: "event",
  },
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "candidate",
        type: "address",
      },
    ],
    name: "onboard",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "value",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101d18061001f6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806320965255146100515780633fa4f245146100675780635524107714610070578063a2c21e3914610085575b600080fd5b6000545b60405190815260200160405180910390f35b61005560005481565b61008361007e366004610152565b610098565b005b61008361009336600461016b565b610119565b600081116100dd5760405162461bcd60e51b815260206004820152600e60248201526d4e6f6e2d7a65726f2076616c756560901b604482015260640160405180910390fd5b60008190556040518181527f93fe6d397c74fdf1402a8b72e47b68512f0510d7b98a4bc4cbdf6ac7108b3c59906020015b60405180910390a150565b6040516001600160a01b03821681527f9e1e650789065f31c36bcdbfd3d2fb47057e3eda429ea3e02f1b118e0ad512a89060200161010e565b60006020828403121561016457600080fd5b5035919050565b60006020828403121561017d57600080fd5b81356001600160a01b038116811461019457600080fd5b939250505056fea2646970667358221220d3072f92d1fde428771dac0d1eb094e38f758a85df13be754b2d9bc3d744be7564736f6c634300081c0033";

type TargetContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TargetContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TargetContract__factory extends ContractFactory {
  constructor(...args: TargetContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TargetContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TargetContract__factory {
    return super.connect(runner) as TargetContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TargetContractInterface {
    return new Interface(_abi) as TargetContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TargetContract {
    return new Contract(address, _abi, runner) as unknown as TargetContract;
  }
}
